name: Checkin

on:
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 时间 16:00 执行（北京时间 00:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4

      - name: 🏗️ 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 📦 安装依赖
        run: |
          pip install requests beautifulsoup4

      - name: ✅ 运行签到脚本
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          USER1: ${{ secrets.USER1 }}
          PASS1: ${{ secrets.PASS1 }}
        run: python checkin.py

      - name: 📌 执行完成
        run: echo "签到任务已完成 ✅"
